---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=26
ggplot(ratings, aes(x = rating)) +
    geom_histogram(bins = 10, color = "black", fill = "purple") +
    scale_y_continuous(labels = label_comma()) +
    labs(title = "Number of Ratings at Each Star Level",
      x = "Rating",
      y = "Number of Ratings")

```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean rating and number of ratings
# hint: use the n() function for easy counting within a group
agg_ratings <- ratings %>%
    group_by(movie_id) %>%
    summarize(mean_rating = mean(rating), num_ratings = n())

head(agg_ratings) %>% kable()
```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
# hint: try scale_x_log10() for a logarithmic x axis
ratings %>%
    group_by(movie_id) %>%
    summarize(num_ratings = n()) %>%
    ggplot(aes(x = num_ratings)) +
        geom_density(fill = "purple", alpha = 0.4)  +
        scale_x_log10(labels = label_comma(), 
                      breaks = c(1, 3, 10, 30, 100, 300, 1e3, 3e3, 1e4, 3e4, 1e5)) +
        labs(title = "Distribution of Movie Popularity",
          x = "Number of Ratings",
          y = "Density")
```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=28
# hint: try geom_histogram and geom_density
ratings %>%
    group_by(movie_id) %>%
    summarize(mean_rating = mean(rating)) %>%
    ggplot(aes(x = mean_rating)) +
        geom_density(fill = "purple", alpha = 0.4)  +
        #geom_histogram(aes(y = after_stat(density)), bins = 42, fill = "red", color = "black") 
        labs(title = "Distribution of Mean Ratings by Movie",
          x = "Mean Rating by Movie",
          y = "Density")
```

```{r cdf-movie-pop}
# rank movies by popularity (number of ratings) and compute the cdf, or fraction of all views covered by the top-k movies https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=30
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below

# plot the CDF of movie popularity

movie_cdf <- ratings %>% 
  group_by(movie_id) %>%
  summarize(num_ratings = n()) %>%
  arrange(desc(num_ratings)) %>% 
  mutate(movie_rank = row_number(),
    cdf = cumsum(num_ratings) / sum(num_ratings))

head(movie_cdf) %>% kable() # peek

movie_cdf %>%
    ggplot(aes(x = movie_rank, y = cdf)) +
        geom_line(color = "purple", linewidth = 1) +
        scale_x_continuous(labels = label_comma()) +
        scale_y_continuous(labels = label_percent(), limits = c(0, 1)) +
        labs(title = "CDF of Movie Popularity",
             x = "Movie Rank",
             y = "CDF")
```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings
agg_ratings_user <- ratings %>%
    group_by(user_id) %>%
    summarize(mean_rating = mean(rating), num_ratings = n())

head(agg_ratings_user) %>% kable()
```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here
ratings %>%
    group_by(user_id) %>%
    summarize(num_ratings = n()) %>%
    ggplot(aes(x = num_ratings)) +
        geom_density(fill = "purple", alpha = 0.4)  +
        scale_x_log10(labels = label_comma(), 
                      breaks = c(1, 3, 10, 30, 100, 300, 1e3, 3e3, 1e4, 3e4, 1e5)) +
        labs(title = "Distribution of User Activity",
          x = "Number of User Ratings", 
          y = "Density")
```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2a of this paper:
# note: don't worry about the "null model" lines
# just do the solid lines and dotted line (optional)
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).

#Phase 1: Users who rated at least 10 movies
qualified_users <- ratings %>%
    group_by(user_id) %>%
    summarize(n_ratings = n()) %>%
    filter(n_ratings >= 10)

#Phase 2: Rank movies by popularity (most pop is rank 1)
# like building a "global" leaderboard
movie_ranks <- ratings %>%
    group_by(movie_id) %>%
    summarize(num_ratings = n()) %>%
    arrange(desc(num_ratings)) %>%
    mutate(movie_rank = row_number()) %>% #adds new col
    select(movie_id, movie_rank) #select cols we care about

#Phase 3: find required k for each user's satisfaction levels
# Use join (but which join? left, inner, etc.)
user_sat_thresholds <- ratings %>%
    # Keep intersection which is inner join
    inner_join(qualified_users, by = "user_id") %>%
    inner_join(movie_ranks, by = "movie_id") %>%
    group_by(user_id) %>%
    # Find kth movie rank needed to hit 90% and 100% satisfactoin
    summarize(
        k_100 = max(movie_rank),
        k_90 = quantile(movie_rank, probs = 0.90)
    )

#Phase 4: reshape data
plot_data <- user_sat_thresholds %>%
    pivot_longer(cols = c(k_100, k_90), 
                 names_to = "satisfaction_level", 
                 values_to = "inventory_size") %>%
    mutate(satisfaction_level = case_when(
      satisfaction_level == "k_100" ~ "100% Satisfaction",
      satisfaction_level == "k_90"  ~ "90% Satisfaction"
    )) %>%
    # what's the most scalable?
    # case_when ?
    group_by(satisfaction_level) %>% 
    arrange(inventory_size) %>% 
    mutate(frac_users_satisfied = row_number() / n()) 

# in other words frac_users_satisfied = % of population satified

# caveat: if satisfication_level isn't set case_when gets assigned NA
# case_when executes top down; catch all error at the end 

#Phase 5: Plotting
plot_data %>%
    ggplot(aes(x = inventory_size, y = frac_users_satisfied, color = satisfaction_level)) +
        geom_line(linewidth = 1) +
        scale_x_log10(labels = label_comma()) +
        scale_y_continuous(labels = label_percent(), limits = c(0, 1)) +
        scale_color_manual(values = c("100% Satisfaction" = "green", "90% Satisfaction" = "blue")) +
        labs(title = "User Satisfaction vs. Inventory Size",
             x = "Inventory Size",
             y = "Percent of Users Satisfied",
             color = "Satisfaction Level") +
        theme(legend.position = "bottom")

# limits makes y-axis lock in on 0-100% for CDF
# without legend.position by default the legend appears on the right
# but it occupies a space that could be used for graph so i moved it to bottom
```

```{r Question_quality_of_life_hack}
# Question
# does Rmd have a way to make it into separate chunks but all connect to main chunk?
# somewhat like nesting chunks?
# for example
# ```{r long-tail}

# ```{r long-tail-phase1}
# ```

# ```{r long-tail-phase2}
# ```

# ```

# So i can run the phases separately (easier to debug)
# but it's all under long-tail so it has previous context of my code
```